### ISSUE TITLE
Simplify CSS for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [joshuajameshead/prj-rev-bwfs-dasmoto#5]
It is a good idea to try and simplify the CSS code as much as you can to make the code cleaner and to remove repetitive code. There are several properties shared by multiple selectors in your CSS code, so you can simplify it by applying those to a list of selectors rather than individually. Here is how you might simplify some of these shared properties,

```css
h1, h2, .price {
  font-family: Helvetica;
  font-weight: bold;
}
```
